apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound-deployment
spec:
  selector:
    matchLabels:
      app: unbound-app
  template:
    metadata:
      labels:
        app: unbound-app
    spec:
      containers:
      - name: unbound
        image: docker.io/henriquemcc/unbound
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 53
